In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
train = pd.read_csv('cat-in-the-dat/train.csv')
test = pd.read_csv('cat-in-the-dat/test.csv')

In [4]:
train_id = train['id']
test_id = test['id']
target = train['target']

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 25 columns):
id        300000 non-null int64
bin_0     300000 non-null int64
bin_1     300000 non-null int64
bin_2     300000 non-null int64
bin_3     300000 non-null object
bin_4     300000 non-null object
nom_0     300000 non-null object
nom_1     300000 non-null object
nom_2     300000 non-null object
nom_3     300000 non-null object
nom_4     300000 non-null object
nom_5     300000 non-null object
nom_6     300000 non-null object
nom_7     300000 non-null object
nom_8     300000 non-null object
nom_9     300000 non-null object
ord_0     300000 non-null int64
ord_1     300000 non-null object
ord_2     300000 non-null object
ord_3     300000 non-null object
ord_4     300000 non-null object
ord_5     300000 non-null object
day       300000 non-null int64
month     300000 non-null int64
target    300000 non-null int64
dtypes: int64(8), object(17)
memory usage: 57.2+ MB

In [5]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 24 columns):
id       200000 non-null int64
bin_0    200000 non-null int64
bin_1    200000 non-null int64
bin_2    200000 non-null int64
bin_3    200000 non-null object
bin_4    200000 non-null object
nom_0    200000 non-null object
nom_1    200000 non-null object
nom_2    200000 non-null object
nom_3    200000 non-null object
nom_4    200000 non-null object
nom_5    200000 non-null object
nom_6    200000 non-null object
nom_7    200000 non-null object
nom_8    200000 non-null object
nom_9    200000 non-null object
ord_0    200000 non-null int64
ord_1    200000 non-null object
ord_2    200000 non-null object
ord_3    200000 non-null object
ord_4    200000 non-null object
ord_5    200000 non-null object
day      200000 non-null int64
month    200000 non-null int64
dtypes: int64(7), object(17)
memory usage: 36.6+ MB

In [130]:
df = pd.concat([train.drop(labels=['id','target'],axis=1), test.drop(labels='id',axis=1)])

In [7]:
len(df.columns.values)

23

In [22]:
df_value_counts = df.apply(pd.Series.value_counts)
df_value_counts

,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,nom_4,...,nom_8,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month
0,436334.0,371845.0,308177.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63666.0,128155.0,191823.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,324891.0,NaN,NaN,NaN,NaN,NaN,111495.0,68291.0
T,NaN,NaN,NaN,255913.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23648.0,NaN,NaN,NaN
F,NaN,NaN,NaN,244087.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19471.0,NaN,NaN,NaN
Y,NaN,NaN,NaN,NaN,319640.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14188.0,NaN,NaN,NaN
N,NaN,NaN,NaN,NaN,180360.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3604.0,NaN,NaN,NaN
Green,NaN,NaN,NaN,NaN,NaN,212496.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Blue,NaN,NaN,NaN,NaN,NaN,159928.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Red,NaN,NaN,NaN,NaN,NaN,127576.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Trapezoid,NaN,NaN,NaN,NaN,NaN,NaN,168431.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Square,NaN,NaN,NaN,NaN,NaN,NaN,82633.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Star,NaN,NaN,NaN,NaN,NaN,NaN,76676.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Circle,NaN,NaN,NaN,NaN,NaN,NaN,62118.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Polygon,NaN,NaN,NaN,NaN,NaN,NaN,60452.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Triangle,NaN,NaN,NaN,NaN,NaN,NaN,49690.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168960.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82889.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Snake,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76657.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62366.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Axolotl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59903.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hamster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49225.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168480.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82986.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76596.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61970.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Costa Rica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60213.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49755.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oboe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153692.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Piano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141008.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bassoon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114064.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
av,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512.0,NaN,NaN
DH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,505.0,NaN,NaN
Mf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,470.0,NaN,NaN
jS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,445.0,NaN,NaN
dB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,407.0,NaN,NaN
hL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,345.0,NaN,NaN
oH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,304.0,NaN,NaN
ux,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,296.0,NaN,NaN
pa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.0,NaN,NaN
Kf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,232.0,NaN,NaN
cG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,205.0,NaN,NaN
jp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144.0,NaN,NaN
xP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132.0,NaN,NaN
Jf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN
Id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.0,NaN,NaN
qJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.0,NaN,NaN
eg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN
tv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN
kU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.0,NaN,NaN
vq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,NaN,NaN
Cl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67582.0,41425.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55136.0,33267.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29730.0,18295.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1493.0,941.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43115.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42083.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41100.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37041.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31071.0

In [8]:
pre = ['bin_0','bin_1','bin_2','bin_3','bin_4','nom_0','nom_1','nom_2','nom_3','nom_4','nom_5','nom_6','nom_7','nom_8','nom_9','ord_0','ord_1','ord_2','ord_3','ord_4','ord_5','day','month']
type(pre)

list

In [10]:
%%time
data = pd.get_dummies(df,prefix=pre)

ValueError: Length of 'prefix' (23) did not match the length of the columns being encoded (17).

In [24]:
data.shape

(500000, 16530)

In [15]:
data.shape

(500000, 16513)

In [22]:
cols = data.columns.values.tolist()
train_cols = train.columns.values.tolist()
train_cols

['id',
 'bin_0',
 'bin_1',
 'bin_2',
 'bin_3',
 'bin_4',
 'nom_0',
 'nom_1',
 'nom_2',
 'nom_3',
 'nom_4',
 'nom_5',
 'nom_6',
 'nom_7',
 'nom_8',
 'nom_9',
 'ord_0',
 'ord_1',
 'ord_2',
 'ord_3',
 'ord_4',
 'ord_5',
 'day',
 'month',
 'target']

In [24]:
cols

['bin_0',
 'bin_1',
 'bin_2',
 'ord_0',
 'day',
 'month',
 'bin_3_T',
 'bin_4_Y',
 'nom_0_Green',
 'nom_0_Red',
 'nom_1_Polygon',
 'nom_1_Square',
 'nom_1_Star',
 'nom_1_Trapezoid',
 'nom_1_Triangle',
 'nom_2_Cat',
 'nom_2_Dog',
 'nom_2_Hamster',
 'nom_2_Lion',
 'nom_2_Snake',
 'nom_3_China',
 'nom_3_Costa Rica',
 'nom_3_Finland',
 'nom_3_India',
 'nom_3_Russia',
 'nom_4_Oboe',
 'nom_4_Piano',
 'nom_4_Theremin',
 'nom_5_037bd73d8',
 'nom_5_05950689f',
 'nom_5_05d5943a3',
 'nom_5_06eeaf0aa',
 'nom_5_075ceb58b',
 'nom_5_077fd9465',
 'nom_5_0870880f6',
 'nom_5_0870b0a5d',
 'nom_5_09a4ad97d',
 'nom_5_09ed0a686',
 'nom_5_0b3bec656',
 'nom_5_0bdf8165a',
 'nom_5_0de4acd31',
 'nom_5_0de5598a9',
 'nom_5_0dee9b39a',
 'nom_5_0eb46e992',
 'nom_5_0ef5c1879',
 'nom_5_115a252ba',
 'nom_5_116f7e3e2',
 'nom_5_1305d6e77',
 'nom_5_159a7306f',
 'nom_5_176809a41',
 'nom_5_17a3709ae',
 'nom_5_185ba0a59',
 'nom_5_19db35594',
 'nom_5_1bd1068d9',
 'nom_5_1e6cb96e8',
 'nom_5_1f1702d2f',
 'nom_5_1fd0233cd',
 'nom_5_200009fc3',
 'nom_5_20b10a832',
 'nom_5_2979f0d45',
 'nom_5_29e7f8525',
 'nom_5_2a0e95ba1',
 'nom_5_2cac4af40',
 'nom_5_2cadfed8e',
 'nom_5_2cc9e16b9',
 'nom_5_2d61990e2',
 'nom_5_2e7f4d636',
 'nom_5_2ff007c26',
 'nom_5_30a15b6bd',
 'nom_5_30a530eab',
 'nom_5_321bf770e',
 'nom_5_3263bdce5',
 'nom_5_3271e5526',
 'nom_5_3283ca434',
 'nom_5_33adb4760',
 'nom_5_34ad60330',
 'nom_5_3585ff84b',
 'nom_5_35f65a9bf',
 'nom_5_3685a0904',
 'nom_5_372f6d6ce',
 'nom_5_39647c92a',
 'nom_5_3aa9329e2',
 'nom_5_3aabfa2fc',
 'nom_5_3b5632a0c',
 'nom_5_3fef1a765',
 'nom_5_40e0157b1',
 'nom_5_416a8f3ab',
 'nom_5_4173a0252',
 'nom_5_4464569ee',
 'nom_5_448a66834',
 'nom_5_4604905e7',
 'nom_5_46bd3558d',
 'nom_5_46cab09da',
 'nom_5_472efea17',
 'nom_5_475e79160',
 'nom_5_479fd7aea',
 'nom_5_4845cc770',
 'nom_5_488406659',
 'nom_5_493de6347',
 'nom_5_49f4b29cc',
 'nom_5_4e1b529f6',
 'nom_5_4e28ceffa',
 'nom_5_4ebe94c28',
 'nom_5_4f2b65e1e',
 'nom_5_4f7d91943',
 'nom_5_50f116bcf',
 'nom_5_524b3f349',
 'nom_5_527ded12a',
 'nom_5_5331f98fb',
 'nom_5_534be2753',
 'nom_5_552e3fdc9',
 'nom_5_568550f04',
 'nom_5_586b51342',
 'nom_5_59497d53c',
 'nom_5_59e434d8a',
 'nom_5_5a466e166',
 'nom_5_5a94fc1d9',
 'nom_5_5b0f5acd5',
 'nom_5_5b1a9f841',
 'nom_5_5d18641ff',
 'nom_5_5f7065a42',
 'nom_5_6020a8124',
 'nom_5_60a44c8f4',
 'nom_5_63f642dd9',
 'nom_5_640e1fdd5',
 'nom_5_66669a44f',
 'nom_5_6a2269152',
 'nom_5_6c90f81cd',
 'nom_5_6cd0619e0',
 'nom_5_6f70dc2df',
 'nom_5_6fec43dd8',
 'nom_5_713ad10a7',
 'nom_5_71583d387',
 'nom_5_72f8028dc',
 'nom_5_740fb99a9',
 'nom_5_74bd42d5f',
 'nom_5_76be0b8b1',
 'nom_5_7741f57bd',
 'nom_5_778fdbe56',
 'nom_5_77b08badd',
 'nom_5_79923828f',
 'nom_5_7a12c88d2',
 'nom_5_7da3e4aec',
 'nom_5_7e9cb0f9a',
 'nom_5_7ee26092e',
 'nom_5_81264f81f',
 'nom_5_81f9d3312',
 'nom_5_8266050c6',
 'nom_5_82d1a6dbb',
 'nom_5_83b38aa6b',
 'nom_5_84b0081ad',
 'nom_5_85159d577',
 'nom_5_8573fa81a',
 'nom_5_88707c9ab',
 'nom_5_88917a066',
 'nom_5_88f104c00',
 'nom_5_8cf6c9f74',
 'nom_5_8d5d9f3db',
 'nom_5_8dcf8adfb',
 'nom_5_908a1b9c9',
 'nom_5_91a20b464',
 'nom_5_91bde92fa',
 'nom_5_91c80026f',
 'nom_5_91ea3e4dd',
 'nom_5_92190168b',
 'nom_5_924346656',
 'nom_5_9347491f2',
 'nom_5_96c73114c',
 'nom_5_96c83ac09',
 'nom_5_9ad6558d1',
 'nom_5_9ba4e87a7',
 'nom_5_9bb7ea2da',
 'nom_5_9ecc58be1',
 'nom_5_a21564cab',
 'nom_5_a3471b9d9',
 'nom_5_a35c346aa',
 'nom_5_a3f640358',
 'nom_5_a51e7974e',
 'nom_5_a5c276589',
 'nom_5_a93b89fc9',
 'nom_5_a9ed6dfea',
 'nom_5_ad95dc0ee',
 'nom_5_ade526ba7',
 'nom_5_af088d192',
 'nom_5_b0c8dba76',
 'nom_5_b0faff28f',
 'nom_5_b3b4d25d0',
 'nom_5_b4c8e6595',
 'nom_5_b7bb45938',
 'nom_5_b8d451029',
 'nom_5_b97f51ac4',
 'nom_5_baab29d3d',
 'nom_5_bd40c81f3',
 'nom_5_bd7740b93',
 'nom_5_bdb9fef4a',
 'nom_5_be4578201',
 'nom_5_be5592604',
 'nom_5_c0534106d',
 'nom_5_c08ba4f4c',
 'nom_5_c2843dc45',
 'nom_5_c5725677e',
 'nom_5_ca82ad111',
 'nom_5_caf83c0b5',
 'nom_5_d1b1709e8',
 'nom_5_d3079098d',
 'nom_5_d372c8993',
 'nom_5_d9becff68',
 'nom_5_da60580a8',
 'nom_5_db5e25328',
 'nom_5_dbc448931',
 'nom_5_dbfb714a4',
 'nom_5_dc07effb0',
 'nom_5_dd500b26a',
 'nom_5_ddac78300',
 'nom_5_de04b8750',
 'nom_5_defc6dd20',
 'nom_5_df51b96fc',
 'nom_5_e08092732',
 'nom_5_e0efe9d20',
 'nom_5_e1558b071',
 'nom_5_e428c040e',
 'nom_5_e52fbf1c8',
 'nom_5_e5b29c42b',
 'nom_5_e6f45aa26',
 'nom_5_e70a6270d',
 'nom_5_e7d9ca356',
 'nom_5_e844a1f66',
 'nom_5_e85ec20b5',
 'nom_5_e9c6fe0f7',
 'nom_5_e9f44a509',
 'nom_5_ead12da87',
 'nom_5_eb0004a0b',
 'nom_5_eb69430d6',
 'nom_5_ee55b9d67',
 'nom_5_ef38568df',
 'nom_5_f0c1ceee4',
 'nom_5_f12246592',
 'nom_5_f2a6d797b',
 'nom_5_f2d59cf51',
 'nom_5_f50eb07ae',
 'nom_5_f6c524860',
 'nom_5_f710fca39',
 'nom_5_f7821e391',
 'nom_5_f802a9849',
 'nom_5_f8faea16f',
 'nom_5_f9d17bb93',
 'nom_5_f9e5266f9',
 'nom_5_fa0a88fe9',
 'nom_5_fd04a970f',
 'nom_6_00e9c15b8',
 'nom_6_01455237a',
 'nom_6_017eb57f0',
 'nom_6_0249d8675',
 'nom_6_02d689659',
 'nom_6_0302f1ffc',
 'nom_6_031d49dfc',
 'nom_6_0516fa0d8',
 'nom_6_062cd9a70',
 'nom_6_063f4307d',
 'nom_6_06835761e',
 'nom_6_077e720aa',
 'nom_6_08b282a6c',
 'nom_6_0922e3cb8',
 'nom_6_0958071b5',
 'nom_6_097ff91b3',
 'nom_6_09e796196',
 'nom_6_09f69436c',
 'nom_6_0aeb8fe13',
 'nom_6_0b10fcecc',
 'nom_6_0b17eaec7',
 'nom_6_0b23e3352',
 'nom_6_0bcb379d8',
 'nom_6_0d50f61fd',
 'nom_6_0e2f036b5',
 'nom_6_0ed70b7b1',
 'nom_6_0ef3dda96',
 'nom_6_113deddc9',
 'nom_6_11698a0b3',
 'nom_6_116d9fcd9',
 'nom_6_126a4f83d',
 'nom_6_126c2e512',
 'nom_6_12d88c9c3',
 'nom_6_144279ac1',
 'nom_6_145d17afb',
 'nom_6_153316f52',
 'nom_6_1537295c3',
 'nom_6_1573e6c5f',
 'nom_6_15ea6e2bb',
 'nom_6_1611d2b45',
 'nom_6_162fc2192',
 'nom_6_163b28322',
 'nom_6_16dfb662a',
 'nom_6_1795ef28b',
 'nom_6_17e0c4fa9',
 'nom_6_180a3d6cb',
 'nom_6_1869e63b0',
 'nom_6_18a901239',
 'nom_6_19231be54',
 'nom_6_19505136a',
 'nom_6_1ab5e5ad6',
 'nom_6_1abac47d0',
 'nom_6_1ad744242',
 'nom_6_1b36c0b8c',
 'nom_6_1c34a67d7',
 'nom_6_1c7f1ab58',
 'nom_6_1e5e03a86',
 'nom_6_1ea13ded7',
 'nom_6_1f2e3f148',
 'nom_6_1f40b9ca8',
 'nom_6_1fe17a1fd',
 'nom_6_1ff467489',
 'nom_6_20636817e',
 'nom_6_20dc501c6',
 'nom_6_2119a6f87',
 'nom_6_214f24d39',
 'nom_6_21cb526c2',
 'nom_6_21e2c2d57',
 'nom_6_2268327b2',
 'nom_6_231233ca9',
 'nom_6_23311af90',
 'nom_6_2473094a9',
 'nom_6_24a1bea30',
 'nom_6_2546024d1',
 'nom_6_25d3a1087',
 'nom_6_26bf5ddd9',
 'nom_6_27179d6e5',
 'nom_6_27828c378',
 'nom_6_27e7dbafa',
 'nom_6_2837cf7b8',
 'nom_6_28630a5c8',
 'nom_6_28645754b',
 'nom_6_28b8e5350',
 'nom_6_292dea6ab',
 'nom_6_2936160c7',
 'nom_6_29a854620',
 'nom_6_29b650229',
 'nom_6_29e27ff9d',
 'nom_6_2a22b315e',
 'nom_6_2ae2bd37c',
 'nom_6_2bdc0a5d0',
 'nom_6_2c4223dbd',
 'nom_6_2c7fb8434',
 'nom_6_2cd425e1f',
 'nom_6_2d8a0cf5a',
 'nom_6_2d9852300',
 'nom_6_2df6f79a2',
 'nom_6_2eadb68c5',
 'nom_6_2ed5a94b0',
 'nom_6_2f6efc190',
 'nom_6_309707034',
 'nom_6_309e105f1',
 'nom_6_310b1a988',
 'nom_6_322121abf',
 'nom_6_329124d64',
 'nom_6_32b4b12b1',
 'nom_6_32be571ee',
 'nom_6_32db19124',
 'nom_6_338b8a987',
 'nom_6_3393a0f78',
 'nom_6_339c0fa05',
 'nom_6_34256b89f',
 'nom_6_35f33a8ca',
 'nom_6_36282e811',
 'nom_6_36df19a6e',
 'nom_6_37868097a',
 'nom_6_395941181',
 'nom_6_39981f199',
 'nom_6_3aa0689eb',
 'nom_6_3ac1b8814',
 'nom_6_3ae0ef9f1',
 'nom_6_3afd0489b',
 'nom_6_3b9693870',
 'nom_6_3bac0bd8e',
 'nom_6_3c1c64eaa',
 'nom_6_3c2b12c56',
 'nom_6_3c5d81a52',
 'nom_6_3c7643929',
 'nom_6_3e2b4aac9',
 'nom_6_3e41282ec',
 'nom_6_3e44d44eb',
 'nom_6_3e6a88574',
 'nom_6_3fe2d05f7',
 'nom_6_3fe8e9cba',
 'nom_6_40994d768',
 'nom_6_40ac3fcd5',
 'nom_6_418e9e936',
 'nom_6_42b1cc2fd',
 'nom_6_435fd233e',
 'nom_6_43744dfd9',
 'nom_6_437d8df71',
 'nom_6_43b8c397b',
 'nom_6_44e4c0bba',
 'nom_6_46c89ef8d',
 'nom_6_485fc6466',
 'nom_6_487c32dfa',
 'nom_6_498b2bdcb',
 'nom_6_4990652ec',
 'nom_6_49bceb215',
 'nom_6_49d1a98ef',
 'nom_6_4abed74f5',
 'nom_6_4b967eac4',
 'nom_6_4c183f1ef',
 'nom_6_4c1bdbe7b',
 'nom_6_4c6d8f959',
 'nom_6_4cb66e369',
 'nom_6_4cf47e292',
 'nom_6_4d5fc69ae',
 'nom_6_4daee3baf',
 'nom_6_4dcab4fc8',
 'nom_6_4e6cc8696',
 'nom_6_4f849ad2d',
 'nom_6_4fa3092a4',
 'nom_6_508ff88dc',
 'nom_6_50d7ad46a',
 'nom_6_50e49ea04',
 'nom_6_51477cd88',
 'nom_6_5194690a0',
 'nom_6_51d5f02c1',
 'nom_6_51f28e64c',
 'nom_6_520806ce2',
 'nom_6_527a42dc2',
 'nom_6_54474e8d8',
 'nom_6_54efb1985',
 'nom_6_556aa5d7a',
 'nom_6_55a24a71b',
 'nom_6_55eed5058',
 'nom_6_565a89e93',
 'nom_6_5755f93b2',
 'nom_6_576b27b37',
 'nom_6_5786b10d7',
 'nom_6_57aa15561',
 'nom_6_5a49dd8f6',
 'nom_6_5a5e620b3',
 'nom_6_5b2d457f3',
 'nom_6_5c4ee13e3',
 'nom_6_5cabda141',
 'nom_6_5cbbea089',
 'nom_6_5d47a598c',
 'nom_6_5d7c5c023',
 'nom_6_5e881b059',
 'nom_6_5f57e7d4f',
 'nom_6_5fa8beadb',
 'nom_6_5fc007fd3',
 'nom_6_5fd7600de',
 'nom_6_5ff2c0a8c',
 'nom_6_603232dea',
 'nom_6_6046454de',
 'nom_6_6057ca561',
 'nom_6_612641073',
 'nom_6_628f3170f',
 'nom_6_63d0e6105',
 'nom_6_642fcc7be',
 'nom_6_65aae1692',
 'nom_6_66e2654cb',
 'nom_6_67721d105',
 'nom_6_67bb6c9d7',
 'nom_6_687eaba3e',
 'nom_6_68dd873e4',
 'nom_6_6a53b5f5c',
 'nom_6_6c0354890',
 'nom_6_6c1a5aab7',
 'nom_6_6c90b0073',
 'nom_6_6d2cd10c5',
 'nom_6_6d7f8c086',
 'nom_6_6ea52a806',
 'nom_6_6eaaa8418',
 'nom_6_6f438920f',
 'nom_6_705cb7579',
 'nom_6_708e87b0e',
 'nom_6_70994b28a',
 'nom_6_70a040495',
 'nom_6_70a942fc1',
 'nom_6_7112aaf8e',
 'nom_6_71534b2a8',
 'nom_6_7185a30dc',
 'nom_6_718fd9453',
 'nom_6_71c68195d',
 'nom_6_7322ea1c9',
 'nom_6_73d7ca889',
 'nom_6_73dd803d0',
 'nom_6_7433a98da',
 'nom_6_74e0be86d',
 'nom_6_74e5a0bce',
 'nom_6_75645dad3',
 'nom_6_76ef650e6',
 'nom_6_77ab97a87',
 'nom_6_77ad092c1',
 'nom_6_782664588',
 'nom_6_78500847e',
 'nom_6_788ba7aea',
 'nom_6_78acf1908',
 'nom_6_78e45cd66',
 'nom_6_7909ef46d',
 'nom_6_79a82b7c0',
 'nom_6_7a8736321',
 'nom_6_7cb06ca3c',
 'nom_6_7cd1571c9',
 'nom_6_7d13ad097',
 'nom_6_7d8bc814a',
 'nom_6_7dd3f58e9',
 'nom_6_7e240024b',
 'nom_6_7f3c463a8',
 'nom_6_800577110',
 'nom_6_803f6cece',
 'nom_6_8082e0409',
 'nom_6_80b2270f0',
 'nom_6_81d59974c',
 'nom_6_82f75f00e',
 'nom_6_8367b78fc',
 'nom_6_839a6bcdb',
 'nom_6_83f07ed50',
 'nom_6_8518cecf3',
 'nom_6_854f72f28',
 'nom_6_8584a02f4',
 'nom_6_85885b27e',
 'nom_6_86021cf04',
 'nom_6_860bb37b4',
 'nom_6_8817e18d1',
 'nom_6_882ce2ad7',
 'nom_6_89a937a9f',
 'nom_6_89e65bb86',
 'nom_6_8a34317cb',
 'nom_6_8ad083b20',
 'nom_6_8bb163a87',
 'nom_6_8bbe5580d',
 'nom_6_8bd314488',
 'nom_6_8c8aa1d64',
 'nom_6_8c9d16cc3',
 'nom_6_8cc791aa8',
 'nom_6_8d1b72979',
 'nom_6_8ed6221ae',
 'nom_6_8f897ec3c',
 'nom_6_8fb440e53',
 'nom_6_8fbaca82e',
 'nom_6_8fd64cb59',
 'nom_6_8fec7bc42',
 'nom_6_906c833b2',
 'nom_6_907d87214',
 'nom_6_90ba6c9a6',
 'nom_6_91e1a9d16',
 'nom_6_9218550d8',
 'nom_6_92f461454',
 'nom_6_944239e54',
 'nom_6_944531331',
 'nom_6_9448b8e3b',
 'nom_6_945aa2bc5',
 'nom_6_95572215a',
 'nom_6_95a263224',
 'nom_6_966f4a973',
 'nom_6_96abdfa66',
 'nom_6_96c110558',
 'nom_6_96d5497a4',
 'nom_6_975346729',
 'nom_6_97b6a3518',
 'nom_6_985c40910',
 'nom_6_987d29cca',
 'nom_6_9882f1fa0',
 'nom_6_989a51202',
 'nom_6_9972df3b0',
 'nom_6_99fffb9e9',
 'nom_6_9a16c7c8f',
 'nom_6_9a20c66da',
 'nom_6_9a70de492',
 'nom_6_9a92bb693',
 'nom_6_9abb2ac1a',
 'nom_6_9afd9530d',
 'nom_6_9b1c3c8b7',
 'nom_6_9c5ea36f8',
 'nom_6_9ceb19dd6',
 'nom_6_9d6fa150a',
 'nom_6_9e0a099c7',
 'nom_6_9f53d30ad',
 'nom_6_9fbd66490',
 'nom_6_a028c07af',
 'nom_6_a148d86df',
 'nom_6_a19d81efe',
 'nom_6_a20513779',
 'nom_6_a26bedd00',
 'nom_6_a405b7cf0',
 'nom_6_a406a5f12',
 'nom_6_a520e2537',
 'nom_6_a566016d6',
 'nom_6_a6542cec0',
 'nom_6_a78e38dad',
 'nom_6_a9925d0e5',
 'nom_6_a9b4474f4',
 'nom_6_ac3e34eff',
 'nom_6_ac8c42404',
 'nom_6_acf5b10dd',
 'nom_6_ad1b42856',
 'nom_6_adfb4cba3',
 'nom_6_ae49fec17',
 'nom_6_ae67aec36',
 'nom_6_aed128d19',
 'nom_6_aed51f2c9',
 'nom_6_aee98fa47',
 'nom_6_af9278b96',
 'nom_6_afebf0803',
 'nom_6_b1c48d202',
 'nom_6_b1faf70a1',
 'nom_6_b238965eb',
 'nom_6_b2480a857',
 'nom_6_b2c93e83d',
 'nom_6_b300717cf',
 'nom_6_b321e8ee3',
 'nom_6_b3e59b54a',
 'nom_6_b3f15d742',
 'nom_6_b436c2568',
 'nom_6_b48077cc4',
 'nom_6_b511f5bff',
 'nom_6_b5f4a755a',
 'nom_6_b628a222c',
 'nom_6_b639793f9',
 'nom_6_b69c236cb',
 'nom_6_b73a8ae77',
 'nom_6_b7c276ed2',
 'nom_6_b7d62cb4e',
 'nom_6_b83511180',
 'nom_6_b8caba53f',
 'nom_6_b8cf041db',
 'nom_6_b9f08dc06',
 'nom_6_baef8ee7b',
 'nom_6_baf172f58',
 'nom_6_bb219c9ac',
 'nom_6_bbc311f15',
 'nom_6_bc31d6a6d',
 'nom_6_bc82e0ba0',
 'nom_6_bd47c2363',
 'nom_6_be5a0f5a9',
 'nom_6_bea839b58',
 'nom_6_beb20ea99',
 'nom_6_bedc798e7',
 'nom_6_bf82c01fa',
 'nom_6_c023e914a',
 'nom_6_c06f1b9f7',
 'nom_6_c0e4c4487',
 'nom_6_c0f1061ee',
 'nom_6_c103290d4',
 'nom_6_c135cdf77',
 'nom_6_c3517eaeb',
 'nom_6_c36cea1f7',
 'nom_6_c3c8b7b13',
 'nom_6_c5cf1fdc4',
 'nom_6_c7201df85',
 'nom_6_c73e4dfe1',
 'nom_6_c75b3104a',
 'nom_6_c79a72c72',
 'nom_6_c8436c277',
 'nom_6_c9a951efa',
 'nom_6_c9eedfbc2',
 'nom_6_cad70d692',
 'nom_6_cae4fb7f2',
 'nom_6_cbb210c0a',
 'nom_6_cc8755307',
 'nom_6_cd225807c',
 'nom_6_cd2fa6d62',
 'nom_6_cd8e3a0a7',
 'nom_6_cd94f29d1',
 'nom_6_ce528707a',
 'nom_6_cebefe5b5',
 'nom_6_cefab1020',
 'nom_6_cf82b283d',
 'nom_6_cf8b12b4e',
 'nom_6_cfc8d0828',
 'nom_6_d086fd85e',
 'nom_6_d166613dc',
 'nom_6_d173ac7ca',
 'nom_6_d213f48ed',
 'nom_6_d2c8f2916',
 'nom_6_d2ce6b1c7',
 'nom_6_d39b176b6',
 'nom_6_d405aebc1',
 'nom_6_d42f2b9ec',
 'nom_6_d43e63dc9',
 'nom_6_d44f7245a',
 'nom_6_d4d727716',
 'nom_6_d4fd01769',
 'nom_6_d5febb6ef',
 'nom_6_d6f8634af',
 'nom_6_d70a70804',
 'nom_6_d760c59b0',
 'nom_6_d76a148ab',
 'nom_6_d7fb439cc',
 'nom_6_d804d7926',
 'nom_6_d83ae1b30',
 'nom_6_d88fca3ba',
 'nom_6_d9004c5c2',
 'nom_6_d9025a066',
 'nom_6_d942d1e82',
 'nom_6_d95501ac1',
 'nom_6_d9e131846',
 'nom_6_d9e884466',
 'nom_6_db35bbdcb',
 'nom_6_db64717a3',
 'nom_6_dc0536549',
 'nom_6_dce959dcb',
 'nom_6_dd1dbed78',
 'nom_6_ddb583aa3',
 'nom_6_dee9cf5e9',
 'nom_6_df184daf2',
 'nom_6_df5b440ae',
 'nom_6_df91d98af',
 'nom_6_dfb457d2a',
 'nom_6_dfb9bd114',
 'nom_6_e0664a4d3',
 'nom_6_e10910468',
 'nom_6_e16557b2b',
 'nom_6_e19cd8107',
 'nom_6_e2559b9ab',
 'nom_6_e3396fbd5',
 'nom_6_e495d6f0f',
 'nom_6_e4d51bdd5',
 'nom_6_e550bcc1b',
 'nom_6_e63f69ba1',
 'nom_6_e7073f6a2',
 'nom_6_e77244b50',
 'nom_6_e78ce8c35',
 'nom_6_e7a7bf2e1',
 'nom_6_e866d44ea',
 'nom_6_e97824431',
 'nom_6_ea64fbdeb',
 'nom_6_ea7a1aaf6',
 'nom_6_eaa89fbcc',
 'nom_6_eaaf53f6a',
 'nom_6_eba84389c',
 'nom_6_ebd664cd6',
 'nom_6_ec416c384',
 'nom_6_ec5064acb',
 'nom_6_ec93484e7',
 'nom_6_ec97e8751',
 'nom_6_ed8157b96',
 'nom_6_edb3cf6c8',
 'nom_6_eeda68203',
 'nom_6_ef1f6146b',
 'nom_6_efa38c99d',
 'nom_6_f083d48ad',
 'nom_6_f0c4b23ef',
 'nom_6_f134870d4',
 'nom_6_f14fe8bc5',
 'nom_6_f17881964',
 'nom_6_f24d83141',
 'nom_6_f36d9a851',
 'nom_6_f425b1c8c',
 'nom_6_f461f837c',
 'nom_6_f4689e520',
 'nom_6_f497b97d7',
 'nom_6_f53d92c1a',
 'nom_6_f64fe5bc0',
 'nom_6_f7e243b5d',
 'nom_6_f81cde28d',
 'nom_6_f8c5dc0e0',
 'nom_6_fa2bf5f22',
 'nom_6_fa3f6d36f',
 'nom_6_fa498a5ae',
 'nom_6_fac5eff9e',
 'nom_6_fb1301ef6',
 'nom_6_fb80a804f',
 'nom_6_fbbdfc611',
 'nom_6_fbcb50fc1',
 'nom_6_fc4518443',
 'nom_6_fc613f31d',
 'nom_6_fc791ebea',
 'nom_6_fc88900c4',
 'nom_6_fc88d723d',
 'nom_6_fd2344f16',
 'nom_6_fd9370b9e',
 'nom_6_fe0b55cd2',
 'nom_6_fe0cddc2c',
 'nom_6_fe77c71bd',
 'nom_6_ffc60be1c',
 'nom_7_008f05158',
 'nom_7_00994f749',
 'nom_7_009a419af',
 'nom_7_0108b635e',
 'nom_7_0138d9abe',
 'nom_7_014c66968',
 'nom_7_016867538',
 'nom_7_0171f9241',
 'nom_7_01b8304ae',
 'nom_7_01d32ba52',
 'nom_7_01d49b4e1',
 'nom_7_01d5ecc45',
 'nom_7_01e22241a',
 'nom_7_0208e33dd',
 'nom_7_021629b02',
 'nom_7_022401886',
 'nom_7_0237e9859',
 'nom_7_024eb1d4c',
 'nom_7_027b6d692',
 'nom_7_03338a71c',
 'nom_7_0335c705e',
 'nom_7_03759a488',
 'nom_7_0378e418b',
 'nom_7_038b187fe',
 'nom_7_03c02132c',
 'nom_7_0406d6252',
 'nom_7_040a5f112',
 'nom_7_042524d7d',
 'nom_7_042de6edb',
 'nom_7_04a6f404e',
 'nom_7_04b3d90f2',
 'nom_7_04c9b2e28',
 'nom_7_04d283376',
 'nom_7_04ddac2be',
 'nom_7_055e2ceaa',
 'nom_7_05754af28',
 'nom_7_058d689da',
 'nom_7_0592e1a75',
 'nom_7_06398415b',
 'nom_7_069dabb39',
 'nom_7_06cd3d7c6',
 'nom_7_0777c8b7c',
 'nom_7_077a10d72',
 'nom_7_07bba85ec',
 'nom_7_080f75dce',
 'nom_7_092130a59',
 'nom_7_09394408f',
 'nom_7_0944f3afc',
 'nom_7_095d69ddc',
 'nom_7_097b0f4ce',
 'nom_7_09b286318',
 'nom_7_0ad56da4e',
 'nom_7_0ad84f641',
 'nom_7_0ae0f174d',
 'nom_7_0b5777c67',
 'nom_7_0bcd0782c',
 'nom_7_0c03941f3',
 'nom_7_0c1cfb224',
 'nom_7_0c32434c5',
 'nom_7_0c8f6917a',
 'nom_7_0d07ef795',
 'nom_7_0d10d8f0e',
 'nom_7_0e0637b46',
 'nom_7_0e2c0dc76',
 'nom_7_0e9e2ce06',
 'nom_7_0efe70958',
 'nom_7_0f2c0307f',
 'nom_7_0f32c2778',
 'nom_7_0f6dcae96',
 'nom_7_0fa8e8e91',
 'nom_7_0ff0bc946',
 'nom_7_110d26959',
 'nom_7_11853d9d8',
 'nom_7_125315092',
 'nom_7_12869d632',
 'nom_7_128b3573c',
 'nom_7_12b92841d',
 'nom_7_12d5f6772',
 'nom_7_12e6161c9',
 'nom_7_135f7a68a',
 'nom_7_1361751be',
 'nom_7_137922383',
 'nom_7_13b9cdf40',
 'nom_7_140119499',
 'nom_7_1434bf43e',
 'nom_7_14a99ac1e',
 'nom_7_14bd3d56c',
 'nom_7_1511a4ba7',
 'nom_7_15c34fdba',
 'nom_7_15cd3ca69',
 'nom_7_15dc42a6e',
 'nom_7_16101497f',
 'nom_7_163c27422',
 'nom_7_168469b34',
 'nom_7_1710fcc5e',
 'nom_7_1726041fb',
 'nom_7_1740266ee',
 'nom_7_17b83802f',
 'nom_7_17cc0943c',
 'nom_7_17d7c7e77',
 'nom_7_1811d1f7b',
 'nom_7_184f1e150',
 'nom_7_185418d90',
 'nom_7_1877cffb3',
 'nom_7_18a6a6e60',
 'nom_7_18ae18b53',
 'nom_7_18b5db61b',
 'nom_7_194a64005',
 'nom_7_1a386ffce',
 'nom_7_1a4e9144f',
 'nom_7_1a5ba32f1',
 'nom_7_1aacd0bd9',
 'nom_7_1bc3c85ad',
 'nom_7_1be616f08',
 'nom_7_1c20a27b8',
 'nom_7_1c2bd266e',
 'nom_7_1c3f27dd8',
 'nom_7_1c5f1ab58',
 'nom_7_1c619215d',
 'nom_7_1c6544394',
 'nom_7_1cd2547ac',
 'nom_7_1cde40c7a',
 'nom_7_1cefd8217',
 'nom_7_1cf5b7dd7',
 'nom_7_1d8c23baa',
 'nom_7_1d9ecee83',
 'nom_7_1db7d5172',
 'nom_7_1dcd3d68e',
 'nom_7_1e141d08e',
 'nom_7_1ee0fe875',
 'nom_7_1ee531eb3',
 'nom_7_1f096b2be',
 'nom_7_1f0a92e59',
 'nom_7_1f4a6de2e',
 'nom_7_1fcf153b3',
 'nom_7_202a9d22a',
 'nom_7_2092f3420',
 'nom_7_211e63f08',
 'nom_7_212279bf0',
 'nom_7_212cf5255',
 'nom_7_212e00b86',
 'nom_7_21a9b0580',
 'nom_7_21e5e9342',
 'nom_7_21f8837a1',
 'nom_7_226e2276b',
 'nom_7_22831fffe',
 'nom_7_22b37c7a3',
 'nom_7_22ff79d81',
 'nom_7_234fb5608',
 'nom_7_23adfa078',
 'nom_7_23b77929a',
 'nom_7_23cd7a725',
 'nom_7_2428baa29',
 'nom_7_24668c22c',
 'nom_7_2488ac2fa',
 'nom_7_24beb3378',
 'nom_7_24de1f87d',
 'nom_7_24e9bf7d4',
 'nom_7_24ffacfdc',
 'nom_7_255667eca',
 'nom_7_26160167b',
 'nom_7_26b8375fd',
 'nom_7_27c719804',
 'nom_7_27d6df03f',
 'nom_7_27e0c7992',
 'nom_7_27e8d4511',
 'nom_7_2923091c6',
 'nom_7_29295065b',
 'nom_7_2938f346d',
 'nom_7_2981119ba',
 'nom_7_2a0b3f539',
 'nom_7_2a7678647',
 'nom_7_2a944c174',
 'nom_7_2b017b873',
 'nom_7_2b5df4f24',
 'nom_7_2b6ded08b',
 'nom_7_2bd9e23c6',
 'nom_7_2c0bba8aa',
 'nom_7_2c89fa25b',
 'nom_7_2c8ad6197',
 'nom_7_2c8e13a9f',
 'nom_7_2c9ffeaae',
 'nom_7_2d2ebbd66',
 'nom_7_2d36d7ff3',
 'nom_7_2d3cb7b79',
 'nom_7_2d6fa1af1',
 'nom_7_2d8e816e2',
 'nom_7_2dd9daf45',
 'nom_7_2de101b87',
 'nom_7_2e02d4b69',
 'nom_7_2e1bf3838',
 'nom_7_2e3adf627',
 'nom_7_2e7a6bd7b',
 'nom_7_2fb072e38',
 'nom_7_30192f1f3',
 'nom_7_3066a4c4f',
 'nom_7_30a0fec63',
 'nom_7_30c5eb4c1',
 'nom_7_30c63bd0c',
 'nom_7_30e376986',
 'nom_7_30eb6faad',
 'nom_7_30ec40df0',
 'nom_7_310cb1765',
 'nom_7_313c2d4b2',
 'nom_7_3193c6338',
 'nom_7_31a7192b6',
 'nom_7_31c0ce565',
 'nom_7_31de4f0dc',
 'nom_7_3212ff699',
 'nom_7_321ba5126',
 'nom_7_32487ff99',
 'nom_7_32b5710ac',
 'nom_7_32ec9c00b',
 'nom_7_33149546e',
 'nom_7_33255a8da',
 'nom_7_333b05914',
 'nom_7_33c193609',
 'nom_7_33d450a91',
 'nom_7_342a7cdf6',
 'nom_7_344623c9c',
 'nom_7_345e8dab0',
 'nom_7_3460d7c4b',
 'nom_7_346c81c8f',
 'nom_7_3482f1d44',
 'nom_7_34acd7fa4',
 'nom_7_34b3a61c3',
 'nom_7_34c59d8cc',
 'nom_7_3506befc5',
 'nom_7_352282217',
 'nom_7_35308d2c7',
 ...]

In [21]:
#dropcols = train.drop(labels=['id','target'],axis=1).columns.values.tolist()
#dropcols

['bin_0',
 'bin_1',
 'bin_2',
 'bin_3',
 'bin_4',
 'nom_0',
 'nom_1',
 'nom_2',
 'nom_3',
 'nom_4',
 'nom_5',
 'nom_6',
 'nom_7',
 'nom_8',
 'nom_9',
 'ord_0',
 'ord_1',
 'ord_2',
 'ord_3',
 'ord_4',
 'ord_5',
 'day',
 'month']

In [23]:
#data.drop(labels=['bin_0','bin_1','bin_2','ord_0','day','month'],axis=1,inplace=True)

MemoryError:

In [12]:
d =0
for i in df.columns :
    
    s = len(df[i].value_counts())
    d = d+s
print(d)

16552

In [43]:
month = pd.get_dummies(df['bin_2'],prefix='bin_2')
month

        bin_2_0  bin_2_1
0             1        0
1             1        0
2             1        0
3             1        0
4             1        0
5             0        1
6             0        1
7             0        1
8             0        1
9             1        0
10            1        0
11            1        0
12            1        0
13            0        1
14            0        1
15            0        1
16            1        0
17            1        0
18            0        1
19            0        1
20            1        0
21            1        0
22            1        0
23            1        0
24            1        0
25            1        0
26            1        0
27            1        0
28            0        1
29            1        0
...         ...      ...
199970        1        0
199971        1        0
199972        0        1
199973        1        0
199974        1        0
199975        0        1
199976        1        0
199977        1        0
199978        0        1
199979        1        0
199980        1        0
199981        1        0
199982        1        0
199983        0        1
199984        1        0
199985        0        1
199986        1        0
199987        1        0
199988        1        0
199989        1        0
199990        1        0
199991        0        1
199992        0        1
199993        1        0
199994        0        1
199995        1        0
199996        1        0
199997        0        1
199998        1        0
199999        1        0

[500000 rows x 2 columns]

In [38]:
data['month']

0          2
1          8
2          2
3          1
4          8
5          2
6          4
7          2
8          4
9          2
10        10
11         2
12         3
13         2
14         7
15         9
16        12
17        10
18         2
19        12
20         1
21         4
22         1
23         1
24         9
25         2
26         3
27         7
28        12
29        11
          ..
199970     2
199971     3
199972    11
199973    12
199974     9
199975     3
199976     1
199977    11
199978     1
199979    10
199980    11
199981    10
199982     1
199983     2
199984     3
199985     4
199986     3
199987     3
199988    10
199989     3
199990     8
199991     7
199992    10
199993     8
199994     1
199995     3
199996     2
199997     1
199998     1
199999     2
Name: month, Length: 500000, dtype: int64

In [18]:
pre = ['bin_0','bin_1','bin_2','bin_3','bin_4','nom_0','nom_1','nom_2','nom_3','nom_4','nom_5','nom_6','nom_7','nom_8','nom_9','ord_0','ord_1','ord_2','ord_3','ord_4','ord_5','day','month']

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500000 entries, 0 to 199999
Data columns (total 23 columns):
bin_0    500000 non-null int64
bin_1    500000 non-null int64
bin_2    500000 non-null int64
bin_3    500000 non-null object
bin_4    500000 non-null object
nom_0    500000 non-null object
nom_1    500000 non-null object
nom_2    500000 non-null object
nom_3    500000 non-null object
nom_4    500000 non-null object
nom_5    500000 non-null object
nom_6    500000 non-null object
nom_7    500000 non-null object
nom_8    500000 non-null object
nom_9    500000 non-null object
ord_0    500000 non-null int64
ord_1    500000 non-null object
ord_2    500000 non-null object
ord_3    500000 non-null object
ord_4    500000 non-null object
ord_5    500000 non-null object
day      500000 non-null int64
month    500000 non-null int64
dtypes: int64(6), object(17)
memory usage: 91.6+ MB

In [14]:
df['month'].value_counts()

2     75508
1     68291
3     67863
11    43115
12    42083
4     41425
9     41100
10    37041
7     33267
8     31071
5     18295
6       941
Name: month, dtype: int64

In [15]:
month = pd.get_dummies(df['month'],prefix='month')
month

,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0
5,0,1,0,0,0,0,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,0,0
7,0,1,0,0,0,0,0,0,0,0,0,0
8,0,0,0,1,0,0,0,0,0,0,0,0
9,0,1,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,1,0,0
11,0,1,0,0,0,0,0,0,0,0,0,0
12,0,0,1,0,0,0,0,0,0,0,0,0
13,0,1,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,1,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,1
17,0,0,0,0,0,0,0,0,0,1,0,0
18,0,1,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,1
20,1,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,1,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,0,0
23,1,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,1,0,0,0
25,0,1,0,0,0,0,0,0,0,0,0,0
26,0,0,1,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,1,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,0,1
29,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
199970,0,1,0,0,0,0,0,0,0,0,0,0
199971,0,0,1,0,0,0,0,0,0,0,0,0
199972,0,0,0,0,0,0,0,0,0,0,1,0
199973,0,0,0,0,0,0,0,0,0,0,0,1
199974,0,0,0,0,0,0,0,0,1,0,0,0
199975,0,0,1,0,0,0,0,0,0,0,0,0
199976,1,0,0,0,0,0,0,0,0,0,0,0
199977,0,0,0,0,0,0,0,0,0,0,1,0
199978,1,0,0,0,0,0,0,0,0,0,0,0
199979,0,0,0,0,0,0,0,0,0,1,0,0
199980,0,0,0,0,0,0,0,0,0,0,1,0
199981,0,0,0,0,0,0,0,0,0,1,0,0
199982,1,0,0,0,0,0,0,0,0,0,0,0
199983,0,1,0,0,0,0,0,0,0,0,0,0
199984,0,0,1,0,0,0,0,0,0,0,0,0
199985,0,0,0,1,0,0,0,0,0,0,0,0
199986,0,0,1,0,0,0,0,0,0,0,0,0
199987,0,0,1,0,0,0,0,0,0,0,0,0
199988,0,0,0,0,0,0,0,0,0,1,0,0
199989,0,0,1,0,0,0,0,0,0,0,0,0
199990,0,0,0,0,0,0,0,1,0,0,0,0
199991,0,0,0,0,0,0,1,0,0,0,0,0
199992,0,0,0,0,0,0,0,0,0,1,0,0
199993,0,0,0,0,0,0,0,1,0,0,0,0
199994,1,0,0,0,0,0,0,0,0,0,0,0
199995,0,0,1,0,0,0,0,0,0,0,0,0
199996,0,1,0,0,0,0,0,0,0,0,0,0
199997,1,0,0,0,0,0,0,0,0,0,0,0
199998,1,0,0,0,0,0,0,0,0,0,0,0
199999,0,1,0,0,0,0,0,0,0,0,0,0

In [16]:
day = pd.get_dummies(df['day'],prefix='day')
day

        day_1  day_2  day_3  day_4  day_5  day_6  day_7
0           0      1      0      0      0      0      0
1           0      0      0      0      0      0      1
2           0      0      0      0      0      0      1
3           0      1      0      0      0      0      0
4           0      0      0      0      0      0      1
5           0      1      0      0      0      0      0
6           0      0      0      0      1      0      0
7           0      0      0      1      0      0      0
8           0      0      1      0      0      0      0
9           0      0      1      0      0      0      0
10          0      0      1      0      0      0      0
11          0      0      0      0      0      0      1
12          0      0      1      0      0      0      0
13          0      0      1      0      0      0      0
14          0      0      0      0      0      0      1
15          1      0      0      0      0      0      0
16          0      1      0      0      0      0      0
17          0      0      0      1      0      0      0
18          0      0      1      0      0      0      0
19          1      0      0      0      0      0      0
20          0      0      0      1      0      0      0
21          0      1      0      0      0      0      0
22          1      0      0      0      0      0      0
23          1      0      0      0      0      0      0
24          1      0      0      0      0      0      0
25          0      0      0      1      0      0      0
26          0      1      0      0      0      0      0
27          1      0      0      0      0      0      0
28          0      0      1      0      0      0      0
29          1      0      0      0      0      0      0
...       ...    ...    ...    ...    ...    ...    ...
199970      0      1      0      0      0      0      0
199971      0      0      0      0      0      0      1
199972      0      1      0      0      0      0      0
199973      1      0      0      0      0      0      0
199974      0      1      0      0      0      0      0
199975      0      0      0      0      1      0      0
199976      1      0      0      0      0      0      0
199977      0      0      1      0      0      0      0
199978      0      0      0      0      1      0      0
199979      1      0      0      0      0      0      0
199980      0      0      0      0      0      0      1
199981      0      1      0      0      0      0      0
199982      0      0      1      0      0      0      0
199983      0      0      1      0      0      0      0
199984      0      1      0      0      0      0      0
199985      0      0      0      0      0      0      1
199986      0      0      1      0      0      0      0
199987      0      0      1      0      0      0      0
199988      1      0      0      0      0      0      0
199989      0      0      1      0      0      0      0
199990      0      1      0      0      0      0      0
199991      0      1      0      0      0      0      0
199992      0      0      0      1      0      0      0
199993      0      1      0      0      0      0      0
199994      0      0      0      1      0      0      0
199995      1      0      0      0      0      0      0
199996      0      1      0      0      0      0      0
199997      0      0      1      0      0      0      0
199998      0      1      0      0      0      0      0
199999      0      1      0      0      0      0      0

[500000 rows x 7 columns]

In [17]:
del day,month

In [27]:
for i in df.columns :
    print(i)
    i = pd.get_dummies(df[i],prefix=i)
    #print(i)

bin_0
bin_1
bin_2
bin_3
bin_4
nom_0
nom_1
nom_2
nom_3
nom_4
nom_5
nom_6
nom_7
nom_8
nom_9
ord_0
ord_1
ord_2
ord_3
ord_4
ord_5
day
month

In [26]:
df.columns[0]

'bin_0'

In [9]:
df['ord_1'].value_counts()

Novice         210877
Grandmaster    129143
Contributor     71516
Master          46755
Expert          41709
Name: ord_1, dtype: int64

In [36]:
df['ord_0'].value_counts()

1    324891
2    110784
3     64325
Name: ord_0, dtype: int64

In [37]:
df['ord_2'].value_counts()

Freezing       166065
Lava Hot       106649
Boiling Hot    101263
Cold            56434
Hot             36744
Warm            32845
Name: ord_2, dtype: int64

In [39]:
df['ord_3'].value_counts()

g    60708
l    60357
a    58660
k    47304
i    47016
h    41260
j    41129
f    37139
e    35634
b    19884
o    19010
d    13076
c    11571
n     6701
m      551
Name: ord_3, dtype: int64

In [11]:
df['ord_4'].value_counts().count()

26

In [12]:
df['ord_5'].value_counts().count()

192

In [13]:
df['nom_9'].value_counts().count()

12068

In [33]:
pd.get_dummies(df['ord_1'],prefix='ord_1')

,ord_1_Contributor,ord_1_Expert,ord_1_Grandmaster,ord_1_Master,ord_1_Novice
0,0,0,1,0,0
1,0,0,1,0,0
2,0,1,0,0,0
3,0,0,1,0,0
4,0,0,1,0,0
5,0,0,0,0,1
6,0,0,1,0,0
7,0,0,0,0,1
8,0,0,0,0,1
9,0,1,0,0,0
10,0,0,1,0,0
11,0,0,0,0,1
12,0,0,0,0,1
13,0,0,0,0,1
14,0,0,1,0,0
15,1,0,0,0,0
16,1,0,0,0,0
17,0,0,0,1,0
18,1,0,0,0,0
19,0,0,1,0,0
20,0,1,0,0,0
21,0,0,0,0,1
22,0,0,1,0,0
23,0,0,1,0,0
24,0,0,0,0,1
25,0,0,1,0,0
26,0,0,1,0,0
27,0,0,0,1,0
28,0,0,0,1,0
29,0,1,0,0,0
...,...,...,...,...,...
199970,0,0,0,1,0
199971,0,0,0,1,0
199972,0,0,0,1,0
199973,0,0,0,1,0
199974,0,1,0,0,0
199975,1,0,0,0,0
199976,0,0,1,0,0
199977,0,0,0,1,0
199978,0,0,1,0,0
199979,0,0,0,0,1
199980,1,0,0,0,0
199981,0,0,1,0,0
199982,0,0,0,0,1
199983,0,0,1,0,0
199984,0,0,0,0,1
199985,0,0,0,0,1
199986,0,0,0,0,1
199987,0,0,0,0,1
199988,0,0,1,0,0
199989,0,0,0,0,1
199990,0,0,0,0,1
199991,0,0,1,0,0
199992,0,0,0,0,1
199993,1,0,0,0,0
199994,0,0,0,1,0
199995,0,0,0,0,1
199996,1,0,0,0,0
199997,0,0,0,0,1
199998,0,0,1,0,0
199999,0,0,0,0,1

In [ ]:
ord_0
ord_1
ord_2
ord_3
ord_4
ord_5

In [ ]:
plt.hist(df['ord_1'])

KeyboardInterrupt:

In [17]:
df['ord_5'].head(10)

0    kr
1    bF
2    Jc
3    kW
4    qP
5    PZ
6    wy
7    Ed
8    qo
9    CZ
Name: ord_5, dtype: object

In [163]:
ordn = df[['ord_0','ord_1','ord_2','ord_3','ord_4','ord_5']]

In [164]:
ordn.head(10)

   ord_0        ord_1        ord_2 ord_3 ord_4 ord_5
0      2  Grandmaster         Cold     h     D    kr
1      1  Grandmaster          Hot     a     A    bF
2      1       Expert     Lava Hot     h     R    Jc
3      1  Grandmaster  Boiling Hot     i     D    kW
4      1  Grandmaster     Freezing     a     R    qP
5      1       Novice     Freezing     j     E    PZ
6      2  Grandmaster     Lava Hot     g     P    wy
7      1       Novice     Lava Hot     j     K    Ed
8      2       Novice  Boiling Hot     e     V    qo
9      1       Expert     Freezing     h     Q    CZ

In [44]:
ordn['ord_0'].value_counts()

1    324891
2    110784
3     64325
Name: ord_0, dtype: int64

In [90]:
type(ordn['ord_5'].value_counts())

pandas.core.series.Series

In [ ]:
ord_2_dict = {'Freezing':1,'Cold':2,'Warm':3,'Hot':4,'Boiling Hot':5,'Lava Hot':6}
ord_1_dict = {'Novice':1,'Contributor':2,'Expert':3,'Master':4,'Grandmaster':5}

In [ ]:
ord_1_dict = {}

In [71]:
import string
import itertools

low_alfa = dict(zip(string.ascii_lowercase, itertools.count(1)))

upr_alfa = dict(zip(string.ascii_uppercase, itertools.count(1)))

upw = dict(zip(ordlst, itertools.count(1)))

In [84]:
ord5_alf = dict(low_alfa)
ord5_alf.update(upr_alfa)

In [104]:
ord5_alf['d']

4

In [105]:
for i in ordn['ord_5'].value_counts().index:
    s = list(i)
    mult = ord5_alf[s[1]] * ord5_alf[s[0]]
    print(i)
    print(s)
    print(mult)
    break

od
['o', 'd']
60

In [150]:
def val_re(string):
    st = list(string)
    mul = ord5_alf[st[1]] + ord5_alf[st[0]]
    return mul

In [161]:
ordn['ord_5'] = ordn['ord_5'].apply(val_re)

C:\Users\AI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [162]:
ordn['ord_5'].value_counts()

16    31200
17    27737
33    25071
28    23778
29    18827
32    17531
22    17164
19    17005
18    15927
21    15737
36    15076
34    14284
7     13306
44    12572
30    12473
4     11635
40    11505
12    11348
24    11237
25    10955
23    10898
41    10806
14    10686
35    10470
46    10392
15    10341
20     9816
9      9590
47     7553
45     6455
31     5697
27     5503
43     5479
26     5311
10     5127
6      5010
39     4788
38     4736
42     4703
13     4393
8      4265
37     4053
49     3720
11     2927
50     1235
3       975
48      703
Name: ord_5, dtype: int64

In [159]:
ordn['ord_5'].value_counts()

od    8454
fO    5714
Zq    4882
qP    4776
sD    4747
Gb    4720
uS    4650
TZ    4635
ac    4607
Bd    4603
Xi    4560
tP    4547
ek    4537
on    4533
CZ    4475
Eg    4475
Qo    4425
AP    4414
PQ    4411
Xh    4387
gJ    4371
hp    4361
kW    4341
Jc    4275
bF    4265
nh    4243
ri    4243
UO    4213
eQ    4189
cA    4176
      ...
kr     825
IK     809
Os     798
us     793
Ps     708
ud     704
wy     703
dE     698
Ry     597
av     512
DH     505
Mf     470
jS     445
dB     407
hL     345
oH     304
ux     296
pa     264
Kf     232
cG     205
jp     144
xP     132
Jf     120
Id     118
qJ      93
eg      92
tv      70
kU      67
vq      52
Cl      46
Name: ord_5, Length: 192, dtype: int64

In [177]:
ordlst = ordn['ord_5'].value_counts().index.values.tolist()

In [181]:
ordlst

['od',
 'fO',
 'Zq',
 'qP',
 'sD',
 'Gb',
 'uS',
 'TZ',
 'ac',
 'Bd',
 'Xi',
 'tP',
 'ek',
 'on',
 'CZ',
 'Eg',
 'Qo',
 'AP',
 'PQ',
 'Xh',
 'gJ',
 'hp',
 'kW',
 'Jc',
 'bF',
 'nh',
 'ri',
 'UO',
 'eQ',
 'cA',
 'Ed',
 'tM',
 'Kq',
 'lx',
 'su',
 'dP',
 'sV',
 'qo',
 'Qh',
 'MV',
 'be',
 'aP',
 'zU',
 'JX',
 'MC',
 'Dx',
 'Sc',
 'Wv',
 'wu',
 'rZ',
 'ke',
 'xy',
 'Hj',
 'Fo',
 'aM',
 'aO',
 'qv',
 'vy',
 'PA',
 'ut',
 'CU',
 'CL',
 'GJ',
 'kK',
 'Ye',
 'Vf',
 'LE',
 'dh',
 'Fd',
 'sY',
 'Nk',
 'Er',
 'kE',
 'uy',
 'oC',
 'kC',
 'dO',
 'SB',
 'Gx',
 'qX',
 'Dc',
 'Bn',
 'CM',
 'dQ',
 'FI',
 'ex',
 'cp',
 'To',
 'PZ',
 'hh',
 'mc',
 'Bb',
 'KZ',
 'lF',
 'ps',
 'dZ',
 'TR',
 'RP',
 'hT',
 'BE',
 'Ob',
 'YC',
 'KR',
 'dN',
 'Vx',
 'gM',
 'fh',
 'MO',
 'ZS',
 'QM',
 'XI',
 'Uk',
 'Jt',
 'vK',
 'qA',
 'jV',
 'je',
 'NV',
 'Nf',
 'mm',
 'eb',
 'yc',
 'GD',
 'nX',
 'kL',
 'iT',
 'RG',
 'qw',
 'Qb',
 'lL',
 'qK',
 'sn',
 'ZR',
 'Uu',
 'bJ',
 'uJ',
 'll',
 'RL',
 'Ai',
 'aF',
 'mb',
 'oG',
 'kw',
 'ck',
 'DN',
 'ih',
 'rp',
 'eG',
 'yY',
 'Mx',
 'Yb',
 'Wc',
 'yN',
 'Zc',
 'WE',
 'Ml',
 'BA',
 'oK',
 'Rm',
 'cW',
 'Aj',
 'OR',
 'kr',
 'IK',
 'Os',
 'us',
 'Ps',
 'ud',
 'wy',
 'dE',
 'Ry',
 'av',
 'DH',
 'Mf',
 'jS',
 'dB',
 'hL',
 'oH',
 'ux',
 'pa',
 'Kf',
 'cG',
 'jp',
 'xP',
 'Jf',
 'Id',
 'qJ',
 'eg',
 'tv',
 'kU',
 'vq',
 'Cl']

In [182]:
ordlst.sort()

In [183]:
ordlst

['AP',
 'Ai',
 'Aj',
 'BA',
 'BE',
 'Bb',
 'Bd',
 'Bn',
 'CL',
 'CM',
 'CU',
 'CZ',
 'Cl',
 'DH',
 'DN',
 'Dc',
 'Dx',
 'Ed',
 'Eg',
 'Er',
 'FI',
 'Fd',
 'Fo',
 'GD',
 'GJ',
 'Gb',
 'Gx',
 'Hj',
 'IK',
 'Id',
 'JX',
 'Jc',
 'Jf',
 'Jt',
 'KR',
 'KZ',
 'Kf',
 'Kq',
 'LE',
 'MC',
 'MO',
 'MV',
 'Mf',
 'Ml',
 'Mx',
 'NV',
 'Nf',
 'Nk',
 'OR',
 'Ob',
 'Os',
 'PA',
 'PQ',
 'PZ',
 'Ps',
 'QM',
 'Qb',
 'Qh',
 'Qo',
 'RG',
 'RL',
 'RP',
 'Rm',
 'Ry',
 'SB',
 'Sc',
 'TR',
 'TZ',
 'To',
 'UO',
 'Uk',
 'Uu',
 'Vf',
 'Vx',
 'WE',
 'Wc',
 'Wv',
 'XI',
 'Xh',
 'Xi',
 'YC',
 'Yb',
 'Ye',
 'ZR',
 'ZS',
 'Zc',
 'Zq',
 'aF',
 'aM',
 'aO',
 'aP',
 'ac',
 'av',
 'bF',
 'bJ',
 'be',
 'cA',
 'cG',
 'cW',
 'ck',
 'cp',
 'dB',
 'dE',
 'dN',
 'dO',
 'dP',
 'dQ',
 'dZ',
 'dh',
 'eG',
 'eQ',
 'eb',
 'eg',
 'ek',
 'ex',
 'fO',
 'fh',
 'gJ',
 'gM',
 'hL',
 'hT',
 'hh',
 'hp',
 'iT',
 'ih',
 'jS',
 'jV',
 'je',
 'jp',
 'kC',
 'kE',
 'kK',
 'kL',
 'kU',
 'kW',
 'ke',
 'kr',
 'kw',
 'lF',
 'lL',
 'll',
 'lx',
 'mb',
 'mc',
 'mm',
 'nX',
 'nh',
 'oC',
 'oG',
 'oH',
 'oK',
 'od',
 'on',
 'pa',
 'ps',
 'qA',
 'qJ',
 'qK',
 'qP',
 'qX',
 'qo',
 'qv',
 'qw',
 'rZ',
 'ri',
 'rp',
 'sD',
 'sV',
 'sY',
 'sn',
 'su',
 'tM',
 'tP',
 'tv',
 'uJ',
 'uS',
 'ud',
 'us',
 'ut',
 'ux',
 'uy',
 'vK',
 'vq',
 'vy',
 'wu',
 'wy',
 'xP',
 'xy',
 'yN',
 'yY',
 'yc',
 'zU']

In [184]:
upw = dict(zip(ordlst, itertools.count(1)))